### ISSUE TITLE
[Feature request] 3/4 side camera when zooming

### ISSUE THREAD

**Issue by benoitheylens** [Lanrutcon/CatchTheWind#14]
Hi there,

While I love this addon, sometimes it's a bit odd when you arrive in front of a quest giver from face. It zooms and you don't see the quest giver and only the back of your character.

I think it would be great if the camera kept the same zoom modifier but go 3/4 left or right (I don't know, I think the quest aera are quite wide enough to avoid any camera issue). 

At least it could be an option, what do you think ?

I think it could add a more dramatic and cinematic effect to the quest.

**Comment by Lanrutcon** [comment]
Yes. In a near future, I'll add an option to modify camera positions. Then players can set there close up camera with an angle if they want.

Thanks for your suggestion.

**Comment by Lanrutcon** [comment]
Yes. In a near future, I'll add an option to modify camera positions. Then players can set there close up camera with an angle if they want.

Thanks for your suggestion.

**Comment by Cieper** [comment]
I've used [DynamicCam](https://mods.curse.com/addons/wow/dynamiccam) for this for now. It works quite well, and really improves the feel even more so.

**Comment by benoitheylens** [comment]
They say on the addon's page that it's discontinued ...
Seems great at first, but can you control camera while in combat (like zoom out manually) when you face pvp enemies (to get a bigger and cleaner view of what's around) ?
Anyway, it could be a nice feature to add : the shoulder view from actioncam is a lot like what I was thinking about for CTW.

**Comment by Lanrutcon** [comment]
Hello again.

Sadly, ActionCam feature was disabled during Legion beta with the reason of "motion-sickness" reported by some players.

I added an option to save the current view (i.e. the current camera position) and use it as "interaction" camera position. So, instead of using the default Blizzard view (character's back), you can now set a different camera view.

Thanks for your suggestion.

Implemented in: https://github.com/Lanrutcon/CatchTheWind/commit/18e47d190f0a967307f764c209d08ef3e8f2adc1
