### ISSUE TITLE
Item compare is no longer working as it was

### ISSUE THREAD

**Issue by Hollthulhu** [Lanrutcon/CatchTheWind#18]
Before today, my item rewards always showed the comparison tooltip without having to hold or press any button. Now, there is no way to see item comparison. I have even tried pressing shift, and it tries to open a compare tooltip, but remains invisible. How do I know this? Because I see a blue floating check mark from one of my addons for tracking transmog pieces show up.. but nothing else, not even a frame. Hopefully this can be fixed, until then I will have to stop using this addon.

**Comment by Lanrutcon** [comment]
Hello.

In the latest version, I decided to add a modifier (in this case, _shift_) in order to check the comparing tooltips.

Currently, the comparing tooltips will only show if you are holding _shift_ before mouseovering a reward.
This issue (https://github.com/Lanrutcon/CatchTheWind/issues/17) tells everything that you need to know.

If your issue is something different, then add more information.

Have a nice day.

**Comment by Lanrutcon** [comment]
Fixed in: https://github.com/Lanrutcon/CatchTheWind/commit/2c8c173089f88182d03eabcd014067bb0ab1a066

Thanks for reporting.
