### ISSUE TITLE
[Enhancement] Use ActionCam for zoom

### ISSUE THREAD

**Issue by benoitheylens** [Lanrutcon/CatchTheWind#25]
Hi !
I messed up a bit with the camera to find a suitable zoom for a more dramatic effect but I think I'll have to try with "action cam". I think it's still there in blizzard's code. I like the "simple" zoom effect, but 9 times out of 10, it zooms on your back and you don't see anything. With action cam, at least, you get a "shoulder zoom" and can see the NPC that gives you the quest :).

The most awesome feature would be to point the camera automatically to the center of the NPC Char box, so for tall npc quest givers like big dragons, you would see something else than just their feets.

We could also hardcode camera angles and zooms for each size of quest givers ;).

Thank you for all you did so far : great work, I use it over Storyline now !

**Comment by Lanrutcon** [comment]
Hello.

If I'm not mistaken, Blizzard removed _ActionCam_ a couple of weeks before the launch, (i.e. during the beta).
I did some quick tests in-game (e.g. /console ActionCam full) and nothing happened.


There was a cool addon that used it as "main engine", [DynamicCam](https://mods.curse.com/addons/wow/dynamiccam). But after the "nerf", it just a "simple" camera addon. I still recommend it if you want to "automatize" your camera during certain events (e.g. in combat, flying, npc interaction, etc...). It also "fixed" interactions with big NPCs, zooming out in those situations (dunno if the addon still does this).

I hope Blizzard brings the _ActionCam_ back, because it's a really cool feature, and more options is always good.


Last but not least, in the last major version (v1.5), I added an option to use a different interaction camera position. So, you can set up a camera with a slight angle to see the NPC.

**Comment by Lanrutcon** [comment]
Since Blizzard re-added this feature in 7.1, I will try to "exploit" this feature in the next version.

**Comment by benoitheylens** [comment]
Could not be more awesome than that with ActionCam :D !

**Comment by Lanrutcon** [comment]
The "ActionCam" can now be enabled in the addon's option.

Implemented in: https://github.com/Lanrutcon/CatchTheWind/commit/85defdcbc83c3dfd4827d5fa3a0f5e3cdb928e89
