### ISSUE TITLE
[Enhancement]Zooming happens on any npc you talk to

### ISSUE THREAD

**Issue by JBurlison** [Lanrutcon/CatchTheWind#9]
It zooms in when I talk to any npc, a vendor AH even my bank.

It would be nice if it only zoomed when you started reading quest text instead of every time you clicked on someone. Its kinda annoying to have to re-adjust my camera every time. Also on that note, it should put your camera back to where it was, right now it seems to have some kind of default position. Maybe if you cant get where the camera is have players be able to set where to zoom back out to?

**Comment by JBurlison** [comment]
Is this possible?

**Comment by Lanrutcon** [comment]
Hello and sorry for the late reply.

So, 2/3 are already implemented in the latest version. CTW won't zoom when talking to NPC without quest options and there is an option to use your camera instead of Blizzard default views (i.e. it will return to you camera position after interacting with a NPC).

The only thing that is missing is: zooming on quest select instead of NPC interaction. In my opinion, it's better this way because it zooms only once (how it works currently). If the NPC has 4 quests, you would zoom 4 times, back and forth, with your suggestion.

I got some reports of motion-sickness in the firsts version (when all NPC were affected with zoom), so I can't afford more zoom in/out at every quest selection.
Also, for players with more sensitivity, it's possible to disable camera zooms.
